# Generated by Django 4.0.3 on 2022-10-21 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='room_images/default.jpg', upload_to='car_image')),
                ('modalNo', models.IntegerField()),
                ('carname', models.CharField(max_length=50)),
                ('registrationNo', models.IntegerField()),
                ('category', models.CharField(choices=[('car', 'car'), ('bus', 'bus'), ('Sedan', 'Sedan')], max_length=10)),
                ('price', models.IntegerField()),
                ('day', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
